adapted script for portability and better error msgs

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,10 +1,15 @@
-#!/bin/bash
-mkdir tools
+#!/bin/sh
+mkdir -p tools
 cd tools
 
 if [ ! -e "sbt-launch.jar" ]
 then
- wget http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch//0.12.1/sbt-launch.jar	
+  wget http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch//0.12.1/sbt-launch.jar	
+  if [ ! -s "sbt-launch.jar" ]
+  then
+    echo >&2 "ERROR: Could not download SBT"
+    exit 1
+  fi  
 fi
 	
 cd ..
